server:
  port: ${APP_PORT:8080}

logging:
  level:
    org:
      springframework:
        security: info

spring:
  application:
    name: ${APP_NAME:unnamed}
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:hsqldb:file:./production
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    # HikariCP配置:
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
rsa:
  key:
    pubKeyFile: rsa_pub
    priKeyFile: rsa_pri
    
pebble:
  suffix:
  cache: false


---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:hsqldb:file:./testdb
server:
  port: 8000