server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: ${APP_NAME:unnamed}
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
      
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: create
#        dialect: org.hibernate.dialect.HSQLDialect
#        new_generator_mappings: false
#        format_sql: true
#        show_sql: true
  datasource:
    url: jdbc:hsqldb:file:testdb
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    # HikariCP配置:
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
pebble:
  suffix:
  cache: false

---
spring:
  profiles: test
server:
  port: 8000