server:
  port: ${APP_PORT:8080}

logging:
  level:
    org:
      springframework:
        security: info

spring:
  application:
    name: ${APP_NAME:unnamed}
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:hsqldb:file:testdb
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    # HikariCP配置:
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
key:
  pubKeyFile: "private"
  priKeyFile: "publice"
rsa:
  key:
    pubKeyFile: "private"
    priKeyFile: "publice"
    
pebble:
  suffix:
  cache: false


---
spring:
  profiles: test
server:
  port: 8000